name: bahrain_manpower
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_email_sender: ^5.1.0
  dio: ^4.0.4
  provider: ^6.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.18
  shared_preferences: ^2.0.12
  carousel_slider: ^4.0.0
  geocoding: ^2.0.0
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  youtube_player_flutter: ^8.0.0
  geolocator: ^7.7.1
  webview_flutter: ^2.0.4
  expandable: ^5.0.1
  firebase: ^9.0.2
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  flutter_local_notifications: ^9.3.2
  google_maps_flutter: ^2.1.1
  font_awesome_flutter: ^9.2.0
  adaptive_action_sheet: ^2.0.1
  image_picker: ^0.8.4+5
  bubble: ^1.2.1
  flutter_html: ^2.1.5
  lazy_load_scrollview: ^1.3.0
  flutter_math_fork: ^0.5.0
  rating_dialog: ^2.0.3
  new_version: ^0.3.0
  share: ^2.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - i18n/ar.json
    - i18n/en.json
    - assets/icon/

  fonts:
    - family: DroidKufi
      fonts:
        - asset: assets/fonts/DroidKufiRegular.ttf
        - asset: assets/fonts/DroidKufiBold.ttf
          weight: 700

